name: Go

on:
  push:
    tags:
      - '*'
    branches:
      - 'main'
    pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        include:
#          - goarch: amd64
#            goos: linux
#          - goarch: amd64
#            goos: darwin
#          - goarch: arm64
#            goos: linux
#          - goarch: arm64
#            goos: darwin
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fetch all tags
        run: git fetch --force --tags
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Install Dependencies
        run: go mod tidy
      - name: Build
#        run: |
#          chmod +x MAKE.sh
#          ./MAKE.sh
        run: go build
      - name: Add $GITHUB_WORKSPACE to git safe.directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'