name: Go

on:
  push:
    branches: [ "main" ]
    tage:
      - '*'
  pull_request:
    branches: [ "main" ]


jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goarch: amd64
            goos: linux
          - goarch: amd64
            goos: darwin
          - goarch: arm64
            goos: linux
          - goarch: arm64
            goos: darwin
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Install Dependencies
        run: go mod tidy
      - name: Build
        run: go build
      - name: rename
        run: |
          chmod +x rollshow
          version=`./rollshow -v`
          ver=`echo ${version:0-5}`
          system=`uname`
          arch=`uname -m`
          echo rollshow_"$ver"_"$system"_"$arch"
          mv rollshow rollshow_"$ver"_"$system"_"$arch"
      - uses: actions/checkout@v2
      - name: Add $GITHUB_WORKSPACE to git safe.directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'